name: lab_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  fluttery_audio: 0.0.4
  sqflite: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  autocomplete_textfield: ^1.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "assets/radio_64.png"
  ios: true
  image_path: "assets/radio_64.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family:  pauseIcon
      fonts:
        - asset: assets/fonts/pause.ttf
    - family:  playIcon
      fonts:
        - asset: assets/fonts/play.ttf
    - family:  play_circled
      fonts:
        - asset: assets/fonts/PlayForDetail.ttf
    - family:  pause_circled
      fonts:
        - asset: assets/fonts/pause_circled.ttf
    - family:  stop_circled
      fonts:
        - asset: assets/fonts/stop_circled.ttf
    - family: AppFont1
      fonts:
        - asset: assets/fonts/Livvic-Black.ttf
        - asset: assets/fonts/Livvic-BlackItalic.ttf
    - family: AppFont2
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Manjari
      fonts:
        - asset: assets/fonts/Manjari-Bold.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
