/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const IconData pause = const IconData(0xe800, fontFamily: 'MyFlutterApp');

  static const IconData stop = const IconData(0xe800, fontFamily: 'pauseIcon');

  static const IconData play = const IconData(0xe801, fontFamily: 'playIcon');

  static const IconData play_circled2 = const IconData(0xe800, fontFamily: 'play_circled');

  static const IconData pause_circled2 = const IconData(0xe800, fontFamily: 'pause_circled');

  static const IconData stop_circled2 = const IconData(0xe800, fontFamily: 'stop_circled');
}
